DoEko/src/DoEko/Models/DoEko/Payment.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;

namespace DoEko.Models.DoEko
{
    

    [Table(name:"Payment")]
    public class Payment
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public Guid PaymentId { get; set; }
        /// <summary>
        /// Amount paid by the customer
        /// </summary>
        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        [Required(ErrorMessage = "{0} jest polem obowiązkowym")]
        [Display(Description = "", Name = "Kwota wpłaty", ShortName = "Kwota")]
        public decimal Amount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} jest polem obowiązkowym")]
        [Display(Description = "", Name = "Data płatności", ShortName = "Data płatności")]
        public DateTime PaymentDate { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "{0} jest polem obowiązkowym")]
        [Display(Description = "", Name = "Data zaksięgowania", ShortName = "Data zaks.")]
        public DateTime PostingDate { get; set; }
        /// <summary>
        /// technical field with source 
        /// </summary>
        public string SourceRow { get; set;}
        /// <summary>
        /// 
        /// </summary>
        public DateTime CreatedAt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Guid CreatedBy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime ChangedAt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Guid ChangedBy { get; set; }
        public Boolean RseFotovoltaic { get; set; }
        public Boolean RseSolar { get; set; }
        public Boolean RseHeatPump { get; set; }

        ///// <summary>
        ///// 
        ///// </summary>
        //[NotMapped]
        //public SurveyType[] Types
        //{
        //    get
        //    {
        //        int[] types = Array.ConvertAll(TypeAsString.Split(';'), int.Parse);

        //        var enuTypes = new SurveyType[types.Count()];

        //        for (int i = 0; i < types.Count(); i++)
        //        {
        //            enuTypes[i] = (SurveyType)types[i];
        //        }
        //        return enuTypes;
        //    }
        //    set
        //    {
        //        var _data = value;
        //        TypeAsString = String.Join(";", _data.Select(p => p.ToString()).ToArray());
        //    }
        //}
        ///// <summary>
        ///// 
        ///// </summary>
        //[EditorBrowsable(EditorBrowsableState.Never)]
        //public string TypeAsString { get; set; }

        public Guid? InvestmentId { get; set; }

        public int ContractId { get; set; }
        /// <summary>
        /// When user marks payment as not applicable for this contract
        /// </summary>
        public Boolean NotNeeded { get; set; }
    }
}

DoEko/src/DoEko/ViewModels/PaymentViewModels/AssignInvestmentViewModel.cs
using DoEko.Migrations.DoEko;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DoEko.ViewModels.PaymentViewModels
{
    public class AssignInvestmentViewModel
    {
        public Payment Payment { get; set; }
        public Guid InvestmentId { get; set; }
        
    }
}

DoEko/src/DoEko/Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DoEko.Models.DoEko;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DoEko.Models.Identity;
using DoEko.Services;
using DoEko.Controllers.Attributes;

namespace DoEko.Controllers
{
    [Authorize(Roles = Roles.Admin)]
    public class PaymentsController : Controller
    {
        private readonly DoEkoContext _context;
        private readonly IFileStorage _fileStorage;
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly AzureStorage _azure;

        public PaymentsController(DoEkoContext context, IFileStorage fileStorage, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _fileStorage = fileStorage;
            _userManager = userManager;
            //_azure = new AzureStorage(configuration.GetConnectionString("doekostorage_AzureStorageConnectionString"));
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AssignInvestment(int ContractId)
        {
            IList<Payment> payments = _context.Payments.Where(p => p.ContractId == ContractId && p.InvestmentId == null && p.NotNeeded == false ).ToList();
            if (!payments.Any())
            {
                return RedirectToAction("Details", "Contracts", new { Id = ContractId });
            }
            //var investments = _context.Contracts
            //    .Where(c => c.ContractId == ContractId)
            //    .Include(c => c.Investments)
            //    .ThenInclude(i => i.Address)
            //    .ThenInclude(a=>a.Commune)
            //    .Single().Investments;
            var investments = _context.Investments
                .Where(i => i.ContractId == ContractId)
                .Include(i => i.Address).ThenInclude(a => a.Commune)
                .Include(i => i.InvestmentOwners).ThenInclude(io=>io.Owner)
                .OrderBy(i => i.Address.SingleLine)
                .ToList();
            var ls = investments
                .Select(i => new SelectListItem
                {
                    Text = i.InvestmentOwners.Count > 0 ? i.Address.SingleLine + ", " +
                            i.InvestmentOwners.FirstOrDefault().Owner.PartnerName1 + ' ' +
                            i.InvestmentOwners.FirstOrDefault().Owner.PartnerName2 :
                            i.Address.SingleLine,
                    Value = i.InvestmentId.ToString()
                }).ToList();
            ViewData["DLInvestments"] = new SelectList(ls, "Value", "Text", null);

            var contract = _context.Contracts.Include(c=>c.Project).SingleOrDefault(c => c.ContractId == ContractId);
            ViewData["ProjectId"] = contract.ProjectId;
            ViewData["ShortDescription"] = contract.Project.ShortDescription;
            ViewData["ContractId"] = contract.ContractId;
            ViewData["ContractNumber"] = contract.Number;

            return View(payments.ToList());
        }

        [HttpPost]
        [RequestFormSizeLimitAttribute(5000, Order = 1)]
        [ValidateAntiForgeryToken(Order = 2)]
        public async Task<IActionResult> AssignInvestment(IList<Payment> Payments)
       {
            _context.CurrentUserId = Guid.Parse(_userManager.GetUserId(User));
            var ContractId = Payments.ElementAt(0).ContractId;
            bool error = true;

            if (ModelState.IsValid)
            {
                if(Payments.Where( p => p.InvestmentId   != null  && 
                                        p.NotNeeded      == false && 
                                        p.RseFotovoltaic == false &&
                                        p.RseHeatPump    == false && 
                                        p.RseSolar       == false ).Any())
                {
                    ModelState.AddModelError(string.Empty, $"Proszę wybrać przynajmniej jedno źródło, jeśli przypisano inwestycję");
                }
                else
                {
                    //
                    Payments.Where(p => p.NotNeeded == true)
                        .ToList().ForEach(p => { p.InvestmentId = null; p.RseFotovoltaic = false; p.RseHeatPump = false; p.RseSolar = false; });

                    //
                    foreach (var item in Payments)
                    {
                        Payment dbp = _context.Payments.Single(p => p.PaymentId == item.PaymentId);

                        dbp.InvestmentId = item.InvestmentId;
                        dbp.NotNeeded = item.NotNeeded;
                        dbp.RseFotovoltaic = item.RseFotovoltaic;
                        dbp.RseHeatPump = item.RseHeatPump;
                        dbp.RseSolar = item.RseSolar;
                        _context.Payments.Update(dbp);
                    }

                    try
                    {
                        //_context.UpdateRange(Payments);
                        int x = await _context.SaveChangesAsync();
                        error = false;
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        throw;
                    }
                }
            }

            if (!error)
            {
                return RedirectToAction("Details", "Contracts", new { Id = ContractId });
            }
            else
            {
                var investments = _context.Investments
                                .Where(i => i.ContractId == ContractId)
                                .Include(i => i.Address).ThenInclude(a => a.Commune)
                                .Include(i => i.InvestmentOwners).ThenInclude(io => io.Owner)
                                .OrderBy(i => i.Address.SingleLine)
                                .ToList();
                var ls = investments
                    .Select(i => new SelectListItem
                    {
                        Text = i.InvestmentOwners.Count > 0 ? i.Address.SingleLine + ", " +
                                i.InvestmentOwners.FirstOrDefault().Owner.PartnerName1 + ' ' +
                                i.InvestmentOwners.FirstOrDefault().Owner.PartnerName2 :
                                i.Address.SingleLine,
                        Value = i.InvestmentId.ToString()
                    }).ToList();
                ViewData["DLInvestments"] = new SelectList(ls, "Value", "Text", null);

                var contract = _context.Contracts.Include(c => c.Project).SingleOrDefault(c => c.ContractId == ContractId);
                ViewData["ProjectId"] = contract.ProjectId;
                ViewData["ShortDescription"] = contract.Project.ShortDescription;
                ViewData["ContractId"] = contract.ContractId;
                ViewData["ContractNumber"] = contract.Number;

                return View(Payments);
            }
        }

        [HttpPost]
        public async Task<IActionResult> UploadPaymentFile(FormCollection Form, int ContractId)
        {
            _context.CurrentUserId = Guid.Parse(_userManager.GetUserId(User));
            bool error = false;
            int index;
            IList<string> msg = new List<string>();


            var file = Request.Form.Files.SingleOrDefault(f => f.FileName.ToLower().Contains(".csv"));
            if (file == null)
            {
                //return Red;
            }

            //_azure.Upload(file, enuAzureStorageContainerType.Contract, ContractId.ToString());
            
            _fileStorage.Upload(file, EnuAzureStorageContainerType.Contract, ContractId.ToString());

            StreamReader sr = new StreamReader(file.OpenReadStream());
            string CsvRecord;
            IList<string> CsvTable = new List<String>();
            while ((CsvRecord = sr.ReadLine()) != null)
            {
                CsvTable.Add(CsvRecord.Replace("\"", ""));
            }

            sr.Close();

            Payment payment;
            //DateTime date;
            //Decimal amount;
            index = 0;
            //
            char separator = ',';
            if (CsvTable.First().Split(separator).Length < 10)
                separator = ';';
            if (CsvTable.First().Split(separator).Length < 10)
            {
                msg.Add("Błąd struktury pliku");
                msg.Add("Nie można rozpoznać separatora (; lub ,)");
                TempData["FileUploadResult"] = 8;
                TempData["FileUploadType"] = "Import Wpłat";
                TempData["FileUploadError"] = msg;
                return RedirectToAction("Details", "Contracts", new { Id = ContractId });
            }

            try
            {
                //Remove header
                try
                {
                    CsvTable.RemoveAt(0);
                }
                catch (Exception)
                { }
                foreach (string CsvLine in CsvTable)
                {
                    index += 1;
                    var LineFields = CsvLine.Split(separator);
                    if (LineFields.Length < 10)
                    {
                        continue;
                    }
                    payment = new Payment {
                        ContractId = ContractId,
                        SourceRow = CsvLine,
                        PaymentDate = DateTime.Parse(LineFields[0].ToString()),
                        PostingDate = DateTime.Parse(LineFields[1].ToString()),
                        Amount = decimal.Parse(LineFields[3].Replace(',','.').ToString())
                    };

DoEko/src/DoEko/Views/Payments/AssignInvestment.cshtml
@model IList<DoEko.Models.DoEko.Payment>

@{
    ViewData["Title"] = "Płatności";
}

<!-- Navigation -->
<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Str. Domowa</a></li>
    <li><a asp-action="Index" asp-controller="Projects">Lista Projektów</a></li>
    <li><a asp-action="Details" asp-controller="Projects" asp-route-Id="@ViewBag.ProjectId">Projekt @ViewBag.ShortDescription)</a></li>
    <li><a asp-action="Details" asp-controller="Contracts" asp-route-Id="@ViewBag.ContractId">Umowa @ViewBag.ContractNumber)</a></li>
    <li class="active">Wpłaty z pliku</li>
</ol>
<!--Title-->
<h2>Lista nieprzypisanych wpłat</h2>

<form asp-action="AssignInvestment" 
      asp-controller="Payments" 
      method="post">
    
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Zapisz">
        <a asp-action="Details" asp-controller="Contracts" asp-route-Id="@ViewBag.ContractId" class="btn btn-default">Anuluj</a>
    </div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row" style="background-color: #f6f6f6; min-height:30px;">
        <div class="col-sm-12">
            <div class="row"><div class="col-sm-12"><br /></div></div>
            <div class="row">
                <div class="col-sm-5"><div class="row"><div class="col-sm-12"><label class="control-label">Szczegóły wpłat</label></div></div></div>
                <div class="col-sm-3"><div class="row"><div class="col-sm-12"><label class="control-label">Przypisanie inwestycji</label></div></div></div>
                <div class="col-sm-3"><div class="row"><div class="col-sm-12"><label class="control-label">Źródło</label></div></div></div>
                <div class="col-sm-1"><div class="row"><div class="col-sm-12"><label class="control-label">Usuń</label></div></div></div>
            </div>
            <div class="row"><div class="col-sm-12"><br/></div></div>
        </div>
    </div>
    <div class="row container-fluid pre-scrollable" style="padding-left:unset;padding-right:unset;">
        <div class="col-sm-12">
            @{
                char separator = ';';
                if (Model.First().SourceRow != null)
                {
                    if (Model.First().SourceRow.Split(separator).Length < 10)
                    {
                        separator = ',';
                    }
                }

            }
            @for (int i = 0; i < Model.Count; i++)
            {

                string background = ((i % 2) == 0) ? "background-color: #f6f6f6;" : "background-color: #ffffff;";
                string payer = "";
                string paytitle = "";
                string payaddress = "";
                if (Model[i].SourceRow != null)
                {
                    var arr = Model[i].SourceRow.Split(separator);

                    payer = arr.Length >= 7 ? arr[7].Replace("Nazwa nadawcy:", "").ToString() : "";
                    payaddress = arr.Length >= 8 ? arr[8].Replace("Adres nadawcy:", "").ToString() : "";
                    paytitle = arr.Length >= 9 ? arr[9].Replace("Tytuł:","").ToString() : "";
                }


                <div class="row" id='@("Record[" + i.ToString() + "]")' style="@(background)">
                    <div class="col-sm-5" style="font-size: smaller">
                        <div class="row"><div class="col-sm-12"><br /></div></div>    
                        <div class="row">
                            <div class="col-sm-3"><label class="control-label">Data wpłaty</label></div>
                            <div class="col-sm-8">@Model[i].PaymentDate.ToShortDateString()</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><label class="control-label">Kwota</label></div>
                            <div class="col-sm-8">@Model[i].Amount.ToString("C", System.Globalization.CultureInfo.GetCultureInfo("pl-PL"))</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><label class="control-label">Nadawca</label></div>
                            <div class="col-sm-8">@payer</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><label class="control-label">Adres</label></div>
                            <div class="col-sm-8">@payaddress</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><label class="control-label">Tytuł</label></div>
                            <div class="col-sm-8">@paytitle</div>
                        </div>      
                        <div class="row"><div class="col-sm-12"><br/></div></div>                  
                    </div>
                    <div class="col-sm-3">
                        <div class="row"><div class="col-sm-12"><br/></div></div>
                        <div class="row">
                            <div class="col-sm-12">
                                <input asp-for="@Model[i].PaymentId" type="hidden">
                                <input asp-for="@Model[i].ContractId" type="hidden">
                                <input type="text" class="form-control input-sm investment-text-search" data-investment-reference='@("[" + i.ToString() + "].InvestmentId")'>
                                <input asp-for="@Model[i].InvestmentId" type="hidden" />
                            </div>
                        </div>
                        <div class="row"><div class="col-sm-12"><br/></div></div>
                        <div class="row">
                            <div class="col-sm-12">
                                <span name="[@i].InvestmentId" class="form-control-static"></span>
                            </div>
                        </div>
                        <div class="row"><div class="col-sm-12"></div></div>
                        <div class="row"><div class="col-sm-12"></div></div>
                        <div class="row"><div class="col-sm-12"></div></div>
                    </div>
                    <div class="col-sm-3">
                        <div class="row"><div class="col-sm-12"><br /></div></div>
                        <div class="row"><div class="col-sm-12"></div></div>
                        <div class="row">
                            <div class="col-sm-12">
                                <label>
                                    <input asp-for="@Model[i].RseFotovoltaic" type="checkbox">
                                    Inst. Fotowolt.
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <label class="">
                                    <input asp-for="@Model[i].RseHeatPump" type="checkbox">
                                    Pompa ciepła
                                </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <label class="">
                                    <input asp-for="@Model[i].RseSolar" type="checkbox">
                                    Inst. Solar.
                                </label>
                            </div>
                        </div>
                        <div class="row"><div class="col-sm-12"></div></div>
                        <div class="row"><div class="col-sm-12"></div></div>
                    </div>
                    <div class="col-sm-1">
                        <div class="row"><div class="col-sm-12"><br /></div></div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-default btn-sm" title="Usuń wpłatę">
                                        <input asp-for="@Model[i].NotNeeded"
                                            type="checkbox" autocomplete="off">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</form>

<form hidden>
    <select id="DLInvestmentList" asp-items="@ViewBag.DLInvestments"></select>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <script type="text/javascript" title="autocomplete">
        function onInvestmentSearchResult(event, ui) {
            //stop further processing
            event.stopPropagation();
            event.preventDefault();

            //search field
            var searchBox = $(event.target);

            //reference field 
            var referenceId = "input[name='" + searchBox.data("investment-reference") + "']";
            var referenceField = $(referenceId);
            referenceField.val(ui.item.value);

            //text field
            var textId = "span[name='" + searchBox.data("investment-reference") + "']";
            var textField = $(textId);
            textField.text(ui.item.label);

            //set value manually, because we're stopping event propagation
            searchBox.val(ui.item.label);
            searchBox.autocomplete("close");

        }

        function onInvestmentSearchBreak(event, data) {
            var searchBox = $(event.target);

            //reference field 
            var referenceId = "input[name='" + searchBox.data("investment-reference") + "']";
            var referenceField = $(referenceId);
            referenceField.val("");

            var textId = "span[name='" + searchBox.data("investment-reference") + "']";
            var textField = $(textId);
            textField.text("");
            
        }

        $(document).ready
           (
               function () {
                   //Prepare investment list
                   var sel = document.getElementById('DLInvestmentList');
                   var investmentList = new Array(sel.options.length);

                   for (var i = 0, n = sel.options.length; i < n; i++) {
                       if (sel.options[i].text)
                       {
                           investmentList[i] = {
                               "label": sel.options[i].text,
                               "value": sel.options[i].value
                           };
                       }
                   }
                   //attach autocomplete field
                   $('.investment-text-search').each
                   (
                       function (index){
                           $(this).autocomplete({ source: investmentList })
                       });

                   //event handler
                   $(document).on("autocompleteselect", onInvestmentSearchResult);
                   $(document).on("input", ".investment-text-search", onInvestmentSearchBreak);
               });
    </script>
}