DoEko/src/DoEko/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DoEko.Models.DoEko;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using DoEko.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using DoEko.Models.DoEko.Survey;
using DoEko.ViewModels.SurveyViewModels;
using DoEko.Models.DoEko.Addresses;
using DoEko.Controllers.Helpers;
using DoEko.ViewComponents.ViewModels;
using Microsoft.AspNetCore.Http;
using DoEko.Services;
using Microsoft.WindowsAzure.Storage.Blob;
using System.IO;
using System.ComponentModel.DataAnnotations;
using DoEko.Controllers.Extensions;

namespace DoEko.Controllers
{
    public enum SurveyMoveResult
    {
        [Display(Name ="Ankieta nie została przeniesiona.")]
        NotMoved = 0,
        [Display(Name = "Ankieta została przeniesiona. Statusy inwestycji pozostały bez zmian.")]
        Moved = 1,
        [Display(Name = "Ankieta została przeniesiona. Zaktualizowano status bierzącej inwestycji.")]
        MovedAndStatusChangeFirst = 3,
        [Display(Name = "Ankieta została przeniesiona. Zaktualizowano status nowej inwestycji.")]
        MovedAndStatusChangeSecond = 5,
        [Display(Name ="Ankieta została przeniesiona. Zaktualizowano statusy obu inwestycji.")]
        MovedAndStatuschangeBoth = 7
    }
    [Authorize()]
    public class SurveysController : Controller
    {
        private readonly DoEkoContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IFileStorage _fileStorage;

        public SurveysController(DoEkoContext context, UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> RoleManager,
            IFileStorage filestorage)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = RoleManager;
            _fileStorage = filestorage;
        }
        
        public async Task<IActionResult> Maintain(Guid Id)
        {
            Survey srv = await _context.Surveys.SingleAsync(s => s.SurveyId == Id);
            switch (srv.Type)
            {
                case SurveyType.CentralHeating:
                    SurveyCentralHeating srvch = await _context.SurveysCH
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.Address)
                        .Include(s=>s.Investment)
                        .ThenInclude(i => i.InvestmentOwners)
                        .Include(s=>s.Investment)
                        .ThenInclude(i=>i.Contract).ThenInclude(c=>c.Project)
                        .SingleAsync(s => s.SurveyId == Id);

                    if (srvch.InspectionDateTime <= DateTime.MinValue)
                    {
                        srvch.InspectionDateTime = null;
                    }

                    return View("MaintainCH", srvch);
                case SurveyType.HotWater:
                    SurveyHotWater srvhw = await _context.SurveysHW
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.Address)
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.InvestmentOwners)
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.Contract).ThenInclude(c => c.Project)
                        .SingleAsync(s => s.SurveyId == Id);
                    if (srvhw.InspectionDateTime <= DateTime.MinValue)
                    {
                        srvhw.InspectionDateTime = null;
                    }
                    return View("MaintainHW", srvhw);
                case SurveyType.Energy:
                    SurveyEnergy srven = await _context.SurveysEN
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.Address)
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.InvestmentOwners)
                        .Include(s => s.Investment)
                        .ThenInclude(i => i.Contract).ThenInclude(c => c.Project)
                        .SingleAsync(s => s.SurveyId == Id);
                    if (srven.InspectionDateTime <= DateTime.MinValue)
                    {
                        srven.InspectionDateTime = null;
                    }
                    return View("MaintainEN", srven);
                default:
                    return NotFound();
            }
        }


        [HttpGet]
        public IActionResult MaintainStepAjax(int stepNo, Guid surveyId)
        {
            SurveyFormStep NextStep;
            Survey Srv;
            Enum RSEType;

            try
            {
                Srv = _context.Surveys
                      .Include(s => s.Investment)
                      .ThenInclude(i => i.InvestmentOwners)
                      .Include(s => s.RoofPlanes)
                      .Include(s => s.PlannedInstall)
                      .Single(s => s.SurveyId == surveyId);

                switch (Srv.Type)
                {
                    case SurveyType.CentralHeating:
                        RSEType = ((SurveyCentralHeating)Srv).RSEType;
                        break;
                    case SurveyType.HotWater:
                        RSEType = ((SurveyHotWater)Srv).RSEType;
                        break;
                    case SurveyType.Energy:
                        RSEType = ((SurveyEnergy)Srv).RSEType;
                        break;
                    default:
                        return BadRequest();
                }

                ////
                NextStep = SurveyFormHelper.Steps[Srv.Type][RSEType].ElementAt(stepNo - 1);
                ////

                //Special logic for Ground/Wall/Roof - next section depends on value of Localization
                if (NextStep == SurveyFormStep.SurveyGround)
                {
                    switch (Srv.PlannedInstall.Localization)
                    {
                        case InstallationLocalization.Roof:
                            NextStep = SurveyFormStep.SurveyRoofPlane;
                            break;
                        case InstallationLocalization.Ground:
                            NextStep = SurveyFormStep.SurveyGround;
                            break;
                        case InstallationLocalization.Wall:
                            NextStep = SurveyFormStep.SurveyWall;
                            break;
                        default:
                            NextStep = SurveyFormStep.SurveyGround;
                            break;
                    }
                }

                //3. Set Attributes passed to viewcomponent controller
                object ViewComponentAttributes;

                switch (NextStep)
                {
                    case SurveyFormStep.InvestmentGeneralInfo:
                        ViewComponentAttributes = new { investmentId = Srv.InvestmentId, mode = "Edit" };
                        break;
                    case SurveyFormStep.InvestmentOwnerData:
                        ViewComponentAttributes = new { investmentId = Srv.InvestmentId, ownerId = Srv.Investment.InvestmentOwners.ElementAt(1).OwnerId };
                        break;
                    case SurveyFormStep.SurveyRoofPlane:
                        //take first roofplane or pass null
                        var roofPlaneId = (Srv.RoofPlanes != null && Srv.RoofPlanes.Count > 0) ? Srv.RoofPlanes.First().RoofPlaneId : Guid.Empty;
                        ViewComponentAttributes = new {  surveyId,  roofPlaneId };
                        break;
                    default:
                        ViewComponentAttributes = new {  surveyId };
                        break;
                }

                return ViewComponent(NextStep.ToString(), ViewComponentAttributes);

            }
            catch(Exception exc)
            {
                if (exc.InnerException != null)
                    return BadRequest(exc.InnerException.Message);
                else
                    return BadRequest(exc.Message);
            }
        }
        [HttpGet]
        public IActionResult MaintainNextStepAjax(string currentStep, Guid surveyId)
        {
            Survey Srv;                //Survey being currently edited
            Enum RSEType;              //RSE Type used to calculate next step
            SurveyFormStep CurrentStep;//Current Step
            SurveyFormStep NextStep;   //Next Step

            int CurrentStepNo = 1;     //Needed only for owner or roofplane section where same component is displayed several times for each item
            int NextStepNo = 1;        //Neede only for owner or roofplane sections 
            //InvestmentOwner IO;        //Repeating section Owners
            //SurveyDetRoof RoofPlane;   //Repeating section Roof Planes
            
            //1. Get Survey Type / RSE Type
            try
            {
                Srv = _context.Surveys
                      .Include(s => s.Investment)
                      .ThenInclude(i => i.InvestmentOwners)
                      .Include(s=>s.RoofPlanes)
                      .Include(s=>s.PlannedInstall)
                      .Single(s => s.SurveyId == surveyId);

                switch (Srv.Type)
                {
                    case SurveyType.CentralHeating:
                        RSEType = (SurveyRSETypeCentralHeating)Srv.GetRSEType();
                        break;
                    case SurveyType.HotWater:
                        RSEType = (SurveyRSETypeHotWater)Srv.GetRSEType();
                        break;
                    case SurveyType.Energy:
                        RSEType = (SurveyRSETypeEnergy)Srv.GetRSEType();
                        break;
                    default:

DoEko/src/DoEko/Views/Shared/Components/SurveyWall/WallCH.cshtml
@model DoEko.Models.DoEko.Survey.SurveyDetWall
@using DoEko.Models.DoEko

<form id="SurveyWall"
      asp-action="EditWallAjax"
      asp-controller="Surveys"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="UPDATE"
      data-ajax-update=""
      data-ajax-failure="SectionPostFailure"
      data-ajax-success="SectionPostCompleted">
    <fieldset>
        <legend>Elewacja</legend>
        <input asp-for="SurveyId" type="hidden" />
    </fieldset>
</form>

DoEko/src/DoEko/Views/Shared/Components/SurveyWall/WallEN.cshtml
@model DoEko.Models.DoEko.Survey.SurveyDetWall
@using DoEko.Models.DoEko

<form id="SurveyWall"
      asp-action="EditWallAjax"
      asp-controller="Surveys"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="UPDATE"
      data-ajax-update=""
      data-ajax-failure="SectionPostFailure"
      data-ajax-success="SectionPostCompleted">
    <fieldset>
        <legend>Elewacja</legend>

        <input asp-for="SurveyId" type="hidden" />
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group-sm">
                    <label asp-for="Azimuth" class="control-label"></label>
                    <input asp-for="Azimuth" class="form-control" />
                    <span asp-validation-for="Azimuth" class="text-danger" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1">
                <div class="form-group-sm">
                    <label asp-for="Height" class="control-label"></label>
                    <input asp-for="Height" class="form-control wallarea" />
                    <span asp-validation-for="Height" class="text-danger" />
                </div>
        
            </div>
            <div class="col-sm-1">
                <div class="form-group-sm">
                    <label asp-for="Width" class="control-label"></label>
                    <input asp-for="Width" class="form-control wallarea" />
                    <span asp-validation-for="Width" class="text-danger" />
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group-sm">
                    <label asp-for="UsableArea" class="control-label"></label>
                    <input asp-for="UsableArea" class="form-control" disabled/>
                    <span asp-validation-for="UsableArea" class="text-danger" />
                </div>
            </div>
        </div>
    </fieldset>

</form>

DoEko/src/DoEko/Views/Shared/Components/SurveyWall/WallHW.cshtml
@model DoEko.Models.DoEko.Survey.SurveyDetWall
@using DoEko.Models.DoEko

<form id="SurveyWall"
      asp-action="EditWallAjax"
      asp-controller="Surveys"
      data-ajax="true"
      data-ajax-method="POST"
      data-ajax-mode="UPDATE"
      data-ajax-update=""
      data-ajax-failure="SectionPostFailure"
      data-ajax-success="SectionPostCompleted">
    <fieldset>
        <legend>Elewacja</legend>

        <input asp-for="SurveyId" type="hidden" />
        <div class="row">
            <div class="col-sm-4">
                <div class="form-group-sm">
                    <label asp-for="Azimuth" class="control-label"></label>
                    <input asp-for="Azimuth" class="form-control" />
                    <span asp-validation-for="Azimuth" class="text-danger" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1">
                <div class="form-group-sm">
                    <label asp-for="Height" class="control-label"></label>
                    <input asp-for="Height" class="form-control wallarea" />
                    <span asp-validation-for="Height" class="text-danger" />
                </div>

            </div>
            <div class="col-sm-1">
                <div class="form-group-sm">
                    <label asp-for="Width" class="control-label"></label>
                    <input asp-for="Width" class="form-control wallarea" />
                    <span asp-validation-for="Width" class="text-danger" />
                </div>
            </div>
            <div class="col-sm-4">
                <div class="form-group-sm">
                    <label asp-for="UsableArea" class="control-label"></label>
                    <input asp-for="UsableArea" class="form-control" disabled />
                    <span asp-validation-for="UsableArea" class="text-danger" />
                </div>
            </div>
        </div>
    </fieldset>

</form>